### ISSUE TITLE
fork version or copy?

### ISSUE THREAD

**Issue by henriquemeira** [albfan/sqlworkbenchj#8]
Hello Alberto. I would like to help this project.

Is it an independent fork version, so, starting a new way, or this one is a copy from original project and for each new release from original you will apply in your project?

tks.

**Comment by albfan** [comment]
Well this is both approaches at same time.

Motivation is to correct some oddities I found on a tool I use on regular basis.

I'm in contact with Thomas Kellerer, original author. He has a svn+ant workflow I didn't  find easy to contribute to. But this repo is a git-svn clone, so you can always find original code here. See #9 for a related issue on that.

From here things start to change. 

To ease develop and dependency changes I have mavenized the project ([Convention over configuration](http://en.wikipedia.org/wiki/Convention_over_configuration)). This is a huge change, but only on layout, not code. You could expect rebases or cherry-picking for this changes from time to time (I mostly have used build_115 but on near future work should be rebased to build_117)

Wether you want to contribute on ant workflow or maven workflow is up to you. If it is a cool change I will reapply it on both sides.

I'm talking with Thomas  about the best way to apply this repo changes on his repo -except from maven which he refuses to use- I have lot of experience on contribute svn from git so that should be no problem, at worst any patch-workflow should be enough.

At the end, here you should find a mix from stable releases for SQL Workbench/J joined with patches, improvements, "quick and dirty solutions" and crazy ideas people want to propose.
